### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [jieyilong/tree-of-thought-puzzle-solver#5]
Hi @jieyilong ,

congratulation to this fantastic paper! Great that you are sharing it open source! I was just wondering under which conditions one could reuse the code and materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by jieyilong** [comment]
Thanks for the reminder Robert @haesleinhuepf! I just added the MIT license:

https://github.com/jieyilong/tree-of-thought-puzzle-solver/blob/main/LICENSE

**Comment by haesleinhuepf** [comment]
Fantastic, thanks so much!
